development:
  clients:
    default:
      database: chat_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: chat_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
